## Trying the PubMed Central ID Converter for humans in JupyterLite

> "A simple library for using the PubMed Central ID Convert API for dealing biomedical and scientific literature in modern Python/Jupyter ecosystems."

Here the demonstration of this package is done in JupyterLite.

----------------

# Use `pmc_id_converter` via Python


Using the functionality of the `pmc_id_converter` via `import` is the easiest if you are using Python or a Python-based Jupyter kernel.

I think this offers much more functionality than the command line if you are going to be using this with Python or Jupyter with a Python-based kernel. Therefor, as it has some more options and abilities than the command line, I'll try to provide examples illustrating many of the options.

Since you may be using this where you'd like, and just using my repo a guiding 'how-to' example, I am going to include installing the script and associated dependencies from the basics. So first run the next cell to set up this environment with the needed dependencies. If you already have them where you are working, you'd skip this step.

In [10]:
%pip install requests pandas

The main functionality of the script is in [the file `core.py` in the package repo](https://github.com/fomightez/PubMed_Central_ID_Converter_for_humans/blob/main/src/PMC_ID_Converter_for_humans/core.py), and so all we really need is to get that. Running the next cell will do that. We'll first set a Python string that is that address and then get that. We'll use `requests` since will need that for the script anyway.

In [2]:
url="https://raw.githubusercontent.com/fomightez/PubMed_Central_ID_Converter_for_humans/refs/heads/main/src/PMC_ID_Converter_for_humans/core.py"
import requests
def fetch_github_file_using_requests(the_url):
    """
    Take a url for a raw GitHub file and return the file content using GitHub's CORS-enabled REST API endpoint
    """
    response = requests.get(the_url)
    response.raise_for_status()  # Raise an exception for non-200 status codes
    return response.text
file_content_string = fetch_github_file_using_requests(url)
with open(url.rsplit("/", 1)[-1], 'w', encoding='utf-8') as output_file:
    output_file.write(file_content_string)

Let's verify that worked:

In [3]:
import os
os.listdir()

['OLDjupyterlite_demo.ipynb',
 'core.py',
 'jupyterlite_demo.ipynb',
 'pyodide',
 'README.md',
 'python.ipynb',
 'data']

Let's first see what our current Python kernel sees as on the `Path` of our system:

In [13]:
import sys
sys.path

['',
 '/lib/python313.zip',
 '/lib/python3.13',
 '/lib/python3.13/lib-dynload',
 '/lib/python3.13/site-packages',
 '/drive']

Note, in your own case, if you know `core.py` is already included along that listing, then skip to trying `from core import PMC_id_convert` below. I am assuming you are using the offered JupyterLite session and working out how to adjust in that case. If you are working elsewhere, you may have to custmize this to set things up so that `from core import PMC_id_convert` works.

LEt's see where we are on the present system with this next command to 'print working directory':

In [5]:
%pwd

'/drive'

So we are in `/drive` and that is not on the list in the `Path` of our system lsited above by what `sys.path` shows, and so let's run the next cell to fix that:

In [6]:
import sys
sys.path.append('/drive')

And verify that was added:

In [7]:
import sys
sys.path

['',
 '/lib/python313.zip',
 '/lib/python3.13',
 '/lib/python3.13/lib-dynload',
 '/lib/python3.13/site-packages',
 '/drive']

If where you put `core.py` was already on the `Path` of your system, or you could move it to there. You wouldn't need the above step.

So now we should be ready to run `from core import PMC_id_convert` and have it work. However, I know from recent experience that just adding the path with `core` to the `Path` isn't enough for JupyterLite. We are going to invalidate the current cache and make sure we redo eveything and then import:

In [14]:
import importlib
importlib.invalidate_caches()
%pip install requests pandas

In [15]:
# Now the main import we have been setting up to perform
from core import PMC_id_convert

Now we are fully set to use the functionality provided by the code, and **once you replace the text `<your_email_here>` in the first case with your email**, you  can run the following code block to demonstrate a way to use the script in JupyterLite:

In [36]:
PMC_id_convert('PMC3531190', email = '<YOUR_EMAIL_NEEDS_TO_BE_HERE>')

A dataframe of the data has been saved as a file in a manner where other software can access it (comma-separated form).
RESULTING DATAFRAME is stored as ==> 'PMC_id_convert_output_df.csv'.
A dataframe of the data has been saved as a file in a manner where other Python programs can access it (pickled form).
RESULTING DATAFRAME is stored as ==> 'PMC_id_convert_output_df.pkl'.

In an ideal world, you'd now be ready to run the following code block to demonstrate many ways to use the script in JupyterLite. And some may work, but most likely will encounter one not working because of network issues and disrupt these all running. But you can at least examine the code and adapt to your needs:  
WAIT, just move to markdwon put output for each in turn below each!! Then say to use the proper demo to really run several.

In [31]:
# PMCID
PMC_id_convert('PMC3531190', email = '<YOUR_EMAIL_NEEDS_TO_BE_HERE>')

# Wait a bit before next request
import time
time.sleep(2)  # 2 second delay

# Multiple IDs
PMC_id_convert('PMC3531190, PMC3531191123, PMC3531191')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# PMID
PMC_id_convert('23193287')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# DOI
PMC_id_convert('10.1093/nar/gks1195')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# multiple DOIs
PMC_id_convert('10.1093/nar/gks1195,10.1007/s13205-018-1330-z')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as a dataframe with dataframe displayed as well (will render in nice style in Jupyter)
PMC_id_convert('PMC3531190,PMC3531191123,PMC3531191', return_df = True)

# Wait a bit before next request
time.sleep(2)  # 2 second delay


# Output data as a dataframe and force a string representation to display, even in Jupyter
print(PMC_id_convert('PMC3531190,PMC3531191123,PMC3531191', return_df = True))

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as a dataframe with the file named with a custom prefix  
PMC_id_convert('PMC3531190,PMC3531191123,PMC3531191', output_prefix = 'custom_file_name_suffix')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Python list as input
python_list_ids = ['PMC3531190','PMC3531191123','PMC3531191']
id_list_as_text = ','.join(python_list_ids)
PMC_id_convert(id_list_as_text, output_prefix = 'shows_can_use_list')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as list of dictionaries
list_of_result_dicts = PMC_id_convert('PMC3531190, PMC3531191', outform = 'dictionaries')

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as a JSON text string
print(PMC_id_convert('PMC3531190, PMC3531191', outform = 'json'))


# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as a JSONL (JSON Lines) text string
print(PMC_id_convert('PMC3531190, PMC3531191', outform = 'jsonl'))

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as JSON text & redirect that to a file when running in IPython/Jupyter
result = PMC_id_convert('PMC3531190, PMC3531191', outform = 'json')
%store result >output.txt

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as JSONL (JSON Lines) text  & redirect that to a file when running in IPython/Jupyter
result = PMC_id_convert('PMC3531190, PMC3531191', outform = 'jsonl')
%store result >output.txt

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as JSON text & redirect that to a file when running in standard Python
result = PMC_id_convert('PMC3531190, PMC3531191', outform='json')
with open('output.txt', 'w') as f:
    f.write(result)

# Wait a bit before next request
time.sleep(2)  # 2 second delay

# Output data as JSONL (JSON Lines) text  & redirect that to a file when running in standard Python
result = PMC_id_convert('PMC3531190, PMC3531191', outform='jsonl')
with open('output.txt', 'w') as f:
    f.write(result)

A dataframe of the data has been saved as a file in a manner where other software can access it (comma-separated form).
RESULTING DATAFRAME is stored as ==> 'PMC_id_convert_output_df.csv'.
A dataframe of the data has been saved as a file in a manner where other Python programs can access it (pickled form).
RESULTING DATAFRAME is stored as ==> 'PMC_id_convert_output_df.pkl'.

<class 'Exception'>: API request failed: ('Connection aborted.', HTTPException("Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.allorigins.win/raw?url=https%3A%2F%2Fpmc.ncbi.nlm.nih.gov%2Ftools%2Fidconv%2Fapi%2Fv1%2Farticles%2F%3Fids%3DPMC3531190%2C%20PMC3531191123%2C%20PMC3531191%26format%3Djson%26tool%3DPMC_ID_Converter_for_humans%26email%3Dthe_test%40example.com'."))
This may be due to:
  - Invalid email address: 'the_test@example.com'
  - Network connectivity issues
  - NCBI API service problems
Please verify your email is valid and try again.

The delays add there are to not slam the proxy I found is needed for JupyterLite. It is a possible drawback that would suggests for certain uses, a typical Python kernel not running with WASM may be a better choice for some uses.

Huh. Now the proxy isn't working conssitently!??! Maybe set it to not tax it so much with that whole block. Like put each one in a different cell? (for now, I tried adding a delay.
Pandas works, right?

In [33]:
import pandas as pd
import numpy as np
df = pd.read_csv('PMC_id_convert_output_df.csv')
df

                   doi       pmcid      pmid requested-id
0  10.1093/nar/gks1195  PMC3531190  23193287   PMC3531190

--------

# Use via a Command Line-like interface  WAIT MOVE THIS UNTIL SECOND, SINCE ODD!! And other way more like `import` with ipyKERNEL !!!!

NOTE: 
JupyterLite doesn't have a bash command shell, so we are going to use Jupyter/IPython `%run` magic to use it similarly where we can provide the ids to act on in the command.

To do this so it easy to follow, we are going to place the main script alongside this notebook.

In [4]:
%pwd

'/drive'

In [1]:
#copy the main script to where this notebook is
import os
os.getcwd()

'/drive/PubMed_Central_ID_Converter_for_humans/notebooks'

In [2]:
import os
os.listdir()

['jupyterlite_demo.ipynb']

In [5]:
from pathlib import Path
# Move to a different directory
Path("/drive/PubMed_Central_ID_Converter_for_humans/src/PMC_ID_Converter_for_humans/core.py").rename("/drive/PubMed_Central_ID_Converter_for_humans/notebooks/core.py")

PosixPath('/drive/PubMed_Central_ID_Converter_for_humans/notebooks/core.py')

In [6]:
import os
os.listdir()

['core.py', 'jupyterlite_demo.ipynb']

Now to try to run the core script:

In [ ]:
%run core_test.py PMC3531190 --email <your_mail_here>

--------

## Advanced Python Use

Pandas is common to use when doing data science in Python and it offers easier handling of large collections of data.  
In this section I provide examples integrating use of `????????????` and Pandas.

For making a dataframe of the results in memore from examples like `PMC_id_convert_output_df.csv`.....

In [34]:
import pandas as pd
import numpy as np
df = pd.read_csv('PMC_id_convert_output_df.csv')
df

                   doi       pmcid      pmid requested-id
0  10.1093/nar/gks1195  PMC3531190  23193287   PMC3531190

------

Enjoy!